spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/rooho/SpringCloud
          search-paths: config-in-cloud/respo
          username: rooho.s.co@gmail.com
          password: K5fEixSyg8mG8SReX1D7b3X

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/